### PR TITLE
Several fixes

### LINKED ISSUE #3: JSON channel should handle failed response gracefully

### LINKED ISSUE #4: JSON channel doesn't support posting image as bytes
This is printed when you try to do it:
```
(node:28003) UnhandledPromiseRejectionWarning: Error: Error: 1 CANCELLED: undefined
...
```

### LINKED ISSUE #5: Make pagination work in the JSON channel
Currently, the JSON channel doesn't respect the `page` and the `perPage` fields.

### LINKED ISSUE #6: Don't default empty Concept value to 1 in the JSON channel
Currently, a concept with no value will default to 1.0 in the JSON channel. This is inconsistent with the gRPC channel where it'll default to 0.0.

Make JSON channel default to 0.0 (this is also what JSON channels in Java and Python do).

### PR DESCRIPTION
**Pull request by rok-clarifai**
This PR fixes several issues found when testing the majority of available endpoints.

Closes #3.
Closes #4.
Closes #5.
Closes #6.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -21,26 +21,63 @@ const packageDefinition = protoLoader.loadSync(
...
-        jsonService[methodName].responseDeserialize = (data) => data;
+
+/*
+ * When sending the data over the JSON channel, if a concept doesn't have a value, the server defaults the value
+ * to 1. With the gRPC channel however, all missing fields get a default value of 0. To do the same in JSON channel
+ * what is done in the default gRPC channel, explicit 0 is set.
+ *
+ * Ideally this would be done dynamically by inspecting the "cl_default_float" custom option of the proto field, but
+ * I'm not sure how to find out whether a field has this set or not.
+ */
```
Comment (zeiler) [inline src/index.js:34]: Is this because we have that custom jsonpb package on backend side?

File: src/custom-json-channel.js [hunk 2]
```diff
@@ -1,6 +1,73 @@
...
+function stringifyBase64(obj) {
+    if (obj.constructor === Array) {
+        return obj.map(stringifyBase64);
+    } else if (obj.constructor === Object) {
+        const processedObject = {}
+        for (const key in obj) {
+            if (obj.hasOwnProperty(key)) {
+                if (key === "base64") {
+                    if (Buffer.isBuffer(obj[key])) {
+                        processedObject[key] = obj[key].toString("base64");
```
Comment (zeiler) [inline src/custom-json-channel.js:17]: Isn’t a buffer the wrong type for a byes field? Isn’t this a user error if they set a buffer? This would send the wrong value if they used the binary channel. We should let grpc decide what to send like in python. When their included json format is used it will convert bytes fields to base64 since json can’t handle them otherwise. But when using the binary channel it doesn’t do that conversion and keeps the bytes as is. Is there no included json format they provide for this language?

File: src/index.js (hunk 1 above)
Comment (zeiler) [reply src/index.js:34]: This also seems like a user error and we should mimic any old defaults on the server side. If they want a positive concept they should set to True and all examples should have that no?

File: src/custom-json-channel.js (hunk 2 above)
Comment (rok-clarifai) [reply src/custom-json-channel.js:17]: @zeiler The default gRPC channel supports setting the `bytes base64` field to either "Buffer" or "string" types. If you set "Buffer", I assume it will automatically send the bytes via the wire. If you set "string" (which must be BASE64 encoded), I assume it will decode BASE64 to binary and only then send it (I haven't confirmed this).

So if we want to have the same support in the JSON channel (so switching between the two is seamless), we must also support both "Buffer" and "string" in it.

Or did I misunderstand your comment?

File: src/index.js (hunk 1 above)
Comment (rok-clarifai) [reply src/index.js:34]: @zeiler Currently, when using the gRPC channel and not setting `value` inside of a `concept` object, the server-side will assume you mean 0 and mark the concept as negative (in all three languages). This code also makes sure the JSON channel behaves the same.

In the code examples, everywhere we want to set a positive concept, we explicitly set the value to 1.

Comment (zeiler) [reply src/index.js:34]: yeah I think it's that `cl_default_float` option on the proto that does this in our json parser. Over time I want to remove all those types of field options though as it's weird to have defaults that are different than the proto defaults (which are if nothing is provided it defaults to the zero value). That's why all the examples have value = 1.0 when it's needed which is good. So the gRPC channel is doing the correct long term thing.

Comment (zeiler) [reply src/index.js:34]: i think i see what you mean now with this code, ok this sounds good as if it doesn't currently have the field it sets value = 0 on json, that's great as it makes that cl_default_float skipped on that backend.

File: src/custom-json-channel.js (hunk 2 above)
Comment (zeiler) [reply src/custom-json-channel.js:17]: the way i understand the bytes field is when using binary grpc channel it doesn't get changed at all. I hope that's true for Buffer or string type. 

then with json the included json_format in python will see any bytes field and base64 encode it when it converts the proto to JSON. This is handled in their formatted so the client that uses it doesn't need to do any special work. so it I think we should just convert any field that is `byte` type (not just named base64 as that is confusing) to base64 for the client in the channel so it matches python (and I assume the other non-js languages). Then all our code examples will be the same, just load an image and set it to the field and our channels will take care of it for you. See if there is a json_format type of thing provided by grpc, there might not as this is already JS.

Comment (zeiler) [reply src/custom-json-channel.js:17]: ah yeah if you can't tell if the proto field type is bytes then maybe the "base64" field name is ok for now. I'm not sure if we have any other byte fields currently.
